server:
  port: 8080
  servlet:
    context-path: /prueba
spring:
  application:
    name: prueba
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true